name: update-flake-lock
on: [push]

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Update flake.lock
        uses: ./
        with:
          pr-title: "feat: update flake.lock"
          pr-labels: |
            dependencies
            automated
